### ISSUE TITLE
ignore if/else not working

### ISSUE THREAD

**Issue by pixelass** [istanbuljs/nyc#595]
Please use the template provided below, when reporting bugs:
-----

## Expected Behavior

The following blocks should be ignored

```js
/* istanbul ignore if */
if (foo === 1) {
  // I should be ignored
} else  /* istanbul ignore else|if */ if (foo === 2) {
/* istanbul ignore else */
} else {
 // don't mind me
}
```

## Observed Behavior

The branches are counted as missing coverage

## Bonus Points! Code (or Repository) that Reproduces Issue

**Code**:
https://github.com/pixelass/paraglider/blob/b8d0e361f9a7d8bd65c96ba45a0784f434faa730/src/glider/index.js#L252

**Coverage**: 
https://coveralls.io/builds/11825267/source?filename=src%2Fglider%2Findex.js#L252

## Forensic Information

**Operating System:** 

OS X Sierra 10.12.5 (16F73)

**Environment Information:** 

I tired these:

* node 6.10.x, npm 3.10.10
* node 8.0.x, npm 5.0.0

1. run the following script:

sh -c 'node --version; npm --version; npm ls' > output.txt

I gave it a try, but...  (See npm & node info above)

```
11:09 $ sh -c 'node --version; npm --version; npm ls' > output.txt
npm ERR! extraneous: archy@1.0.0 <WORKSPACE>/paraglider/node_modules/archy
npm ERR! extraneous: debug-log@1.0.1 <WORKSPACE>/paraglider/node_modules/debug-log
npm ERR! extraneous: istanbul-lib-hook@1.0.7 <WORKSPACE>/paraglider/node_modules/istanbul-lib-hook
npm ERR! extraneous: istanbul-lib-instrument@1.7.2 <WORKSPACE>/paraglider/node_modules/istanbul-lib-instrument
npm ERR! extraneous: istanbul-lib-report@1.1.1 <WORKSPACE>/paraglider/node_modules/istanbul-lib-report
npm ERR! extraneous: istanbul-lib-source-maps@1.2.1 <WORKSPACE>/paraglider/node_modules/istanbul-lib-source-maps
npm ERR! extraneous: istanbul-reports@1.1.1 <WORKSPACE>/paraglider/node_modules/istanbul-reports
npm ERR! extraneous: merge-source-map@1.0.3 <WORKSPACE>/paraglider/node_modules/merge-source-map
npm ERR! extraneous: node-pre-gyp@0.6.34 <WORKSPACE>paraglider/node_modules/node-pre-gyp
npm ERR! extraneous: spawn-wrap@1.2.4 <WORKSPACE>/private/paraglider/node_modules/spawn-wrap
npm ERR! extraneous: test-exclude@4.1.1 <WORKSPACE>/paraglider/node_modules/test-exclude
npm ERR! extraneous: yargs-parser@5.0.0 <WORKSPACE>/paraglider/node_modules/yargs-parser
```

**Comment by pixelass** [comment]
This works but ... (no comment)

```js
/* istanbul ignore next */
if (foo === 1) {
  // I should be ignored
/* istanbul ignore next */
} else /* istanbul ignore next */ if (foo === 2) {
/* istanbul ignore next */
} else {
 // don't mind me
}
```

**Comment by bcoe** [comment]
@pixelass interesting; tldr using `ignore next` seems to ignore the blocks appropriately, but using the more specific `if`, `else` behaves weird? I will need to dig into [the instrumenter](https://github.com/istanbuljs/istanbuljs/tree/master/packages/istanbul-lib-instrument) to see what's going on here.

Feel free to take a peek, if you beat me to the punch.

**Comment by pixelass** [comment]
I actually think `if` and `else` are ignored in general.

**Comment by pixelass** [comment]
I know that this was working in earlier versions of nyc. I just experienced this in the latest release. Prior to that I was using 9.x.x

**Comment by pixelass** [comment]
Here's the RegEx that looks for the comment: https://github.com/istanbuljs/istanbuljs/blob/120d2216e130a00e6372eb5e4f32ea301f678bd1/packages/istanbul-lib-instrument/src/visitor.js#L7

**Comment by bcoe** [comment]
@pixelass I believe this should now be addressed by https://github.com/istanbuljs/istanbuljs/pull/65

Please feel free to reopen if you're continuing to run into issues 👍

**Comment by pke** [comment]
I can confirm that istanbuljs/istanbuljs#65 does not fix the OPs problem.
`/* istanbul ignore if */` still doesn't work. Changing it to `/* istanbul ignore next */` does work though.

**Comment by bcoe** [comment]
@pke interesting, if

**Comment by bcoe** [comment]
@pke interesting, perhaps we could add a more specific test to the instrumenter for the `/* istanbul ignore if */` syntax.

If you have an interest in contributing; even getting a failing test in place would be super helpful. The fact that ignore next works appropriately makes me think that the actual bug fix will be pretty small.

**Comment by pixelass** [comment]
@pke <--- OMG I used to work with this guy. (👋 Hi)

@bcoe I'll be happy to retest. I'm working on a new project just about to set up the tests. This issue will definitely come up sooner or later during the process.

**Comment by pke** [comment]
@pixelass Hi Gregor ;) If you could set up the test it would be great. I am a little short on time atm.

**Comment by davesag** [comment]
I've just found that in running a batch of tests with `nyc` in one test the `/* istanbul ignore if */` comment is respected but in the very next test it is not being respected and I am getting coverage errors.

**Comment by pixelass** [comment]
Moving away from Github. Feel free to reopen if interested.
